# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: whisper_control.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15whisper_control.proto\"M\n\x0cIntroduction\x12\x11\n\tpseudonym\x18\x01 \x01(\t\x12\x17\n\x0ftargetInterface\x18\x02 \x01(\t\x12\x11\n\tsignature\x18\x03 \x01(\x0c\"\x1f\n\nAccessPass\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x62\x06proto3')



_INTRODUCTION = DESCRIPTOR.message_types_by_name['Introduction']
_ACCESSPASS = DESCRIPTOR.message_types_by_name['AccessPass']
Introduction = _reflection.GeneratedProtocolMessageType('Introduction', (_message.Message,), {
  'DESCRIPTOR' : _INTRODUCTION,
  '__module__' : 'whisper_control_pb2'
  # @@protoc_insertion_point(class_scope:Introduction)
  })
_sym_db.RegisterMessage(Introduction)

AccessPass = _reflection.GeneratedProtocolMessageType('AccessPass', (_message.Message,), {
  'DESCRIPTOR' : _ACCESSPASS,
  '__module__' : 'whisper_control_pb2'
  # @@protoc_insertion_point(class_scope:AccessPass)
  })
_sym_db.RegisterMessage(AccessPass)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INTRODUCTION._serialized_start=25
  _INTRODUCTION._serialized_end=102
  _ACCESSPASS._serialized_start=104
  _ACCESSPASS._serialized_end=135
# @@protoc_insertion_point(module_scope)
