# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"4\n\x0cIntroduction\x12\x11\n\tpseudonym\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\tb\x06proto3')



_INTRODUCTION = DESCRIPTOR.message_types_by_name['Introduction']
Introduction = _reflection.GeneratedProtocolMessageType('Introduction', (_message.Message,), {
  'DESCRIPTOR' : _INTRODUCTION,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Introduction)
  })
_sym_db.RegisterMessage(Introduction)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INTRODUCTION._serialized_start=18
  _INTRODUCTION._serialized_end=70
# @@protoc_insertion_point(module_scope)
